uploads = []
generated = []

[[outputs]]
id = "N3muN7neInu2PG45eYTQ8"
uri = "file://attached_assets/generated_audio/music_test_beat.mp3"
type = "audio"
title = "test_beat"

[[outputs]]
id = "W-lO6UrCEstMtYlO2OFMN"
uri = "file://attached_assets/generated_audio/music_url_probe.mp3"
type = "audio"
title = "url_probe"
